"use client";

import { FileData, StatusStep } from "@/types/workspace";
import { useEffect, useRef, useState } from "react";
import {
  SandpackProvider,
  SandpackCodeEditor,
  SandpackPreview,
  useSandpack,
  useSandpackNavigation,
  SandpackFileExplorer,
} from "@codesandbox/sandpack-react";
import { dracula } from "@codesandbox/sandpack-themes";
import {
  Code2,
  Eye,
  Wand2,
  Download,
  Copy,
  Check,
  RotateCcw,
  ExternalLink,
  Loader2,
} from "lucide-react";

const PLACEHOLDER_FILES = {
  "/App.js": {
    code: `import React, { useState } from 'react';
import { Sparkles, Heart, Zap, CheckCircle, ArrowUpRight } from 'lucide-react';

export default function App() {
  const [likes, setLikes] = useState(12);

  return (
    <div className="min-h-screen bg-[#0b0b0f] text-white p-4 sm:p-8 font-sans flex flex-col items-center justify-center antialiased">
      <div className="w-full max-w-xl bg-[#14141c] border border-white/10 rounded-2xl p-6 sm:p-8 shadow-2xl relative overflow-hidden">
        <div className="flex items-center justify-between border-b border-white/10 pb-4 mb-6">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-400">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-base sm:text-lg font-bold text-white tracking-tight">Active Sandbox</h1>
              <p className="text-xs text-zinc-400">Generated by webIQ AI</p>
            </div>
          </div>
          <span className="inline-flex items-center gap-1.5 text-[11px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2.5 py-1 rounded-full">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            Live
          </span>
        </div>

        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5">
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs text-zinc-400">Performance</span>
                <Zap className="w-3.5 h-3.5 text-amber-400" />
              </div>
              <p className="text-2xl font-bold text-white">99.4%</p>
            </div>
            <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5">
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs text-zinc-400">AST Nodes</span>
                <CheckCircle className="w-3.5 h-3.5 text-blue-400" />
              </div>
              <p className="text-2xl font-bold text-white">48</p>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5 text-xs text-zinc-300 leading-relaxed">
            <p>
              Your sandbox is live and interactive. Ask the chat agent on the left to add features or modify this layout.
            </p>
          </div>

          <div className="flex items-center gap-3 pt-2">
            <button
              onClick={() => setLikes((l) => l + 1)}
              className="flex-1 py-2.5 px-4 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-semibold transition-all flex items-center justify-center gap-2 shadow-lg shadow-blue-600/20 cursor-pointer"
            >
              <Heart className="w-4 h-4 fill-white" />
              <span>Applaud ({likes})</span>
            </button>
            <button
              onClick={() => alert("Sandbox ready!")}
              className="py-2.5 px-4 bg-white/5 hover:bg-white/10 text-zinc-200 border border-white/10 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 cursor-pointer"
            >
              <span>Explore</span>
              <ArrowUpRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}`,
  },
};

// ─── Fast, reliable dependencies ──────────────────────────────────────────────
const BASE_DEPENDENCIES: Record<string, string> = {
  "lucide-react": "^0.475.0",
  clsx: "^2.1.1",
  "tailwind-merge": "^2.6.0",
};

const customTheme = {
  ...dracula,
  layout: {
    height: "100%",
    headerHeight: "40px",
  },
};

// ─── Types ────────────────────────────────────────────────────────────────────
export type ActiveTab = "preview" | "code";

export interface CodePanelProps {
  fileData: FileData | null;
  isGenerating?: boolean;
  statusLog?: StatusStep[];
  onImprove?: (userRequest: string) => Promise<void> | void;
  onFixError?: (error: string) => Promise<void> | void;
  onFilePatch?: (patches: FileData) => void;
  appTitle?: string | null;
  isImproving?: boolean;
  isProUser?: boolean;
}

function SandpackInner({
  isGenerating,
  activeTab,
  setActiveTab,
  fileData,
  onImprove,
  isImproving = false,
  isProUser = false,
  appTitle,
}: {
  isGenerating: boolean;
  activeTab: ActiveTab;
  setActiveTab: (t: ActiveTab) => void;
  fileData: FileData | null;
  onImprove?: (userRequest: string) => Promise<void> | void;
  isImproving?: boolean;
  isProUser?: boolean;
  appTitle?: string | null;
}) {
  const { sandpack } = useSandpack();
  const { refresh } = useSandpackNavigation();
  const [copied, setCopied] = useState(false);

  const prevFilesRef = useRef<Record<string, { code: string }>>({});

  useEffect(() => {
    if (!fileData?.files) return;
    const prev = prevFilesRef.current;

    for (const [path, { code }] of Object.entries(fileData.files)) {
      if (prev[path]?.code !== code) {
        sandpack.updateFile(path, code);
      }
    }

    prevFilesRef.current = fileData.files;
  }, [fileData?.files, sandpack]);

  const handleCopyCode = () => {
    const activeFile = sandpack.activeFile;
    const code = sandpack.files[activeFile]?.code || "";
    if (code) {
      navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadCode = () => {
    const activeFile = sandpack.activeFile;
    const code = sandpack.files[activeFile]?.code || "";
    const filename = activeFile.split("/").pop() || "Component.jsx";

    const blob = new Blob([code], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const projectUrl = `webiq.app/sandbox/${
    appTitle
      ? appTitle
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/(^-|-$)/g, "")
      : "live-preview"
  }`;

  return (
    <div className="flex flex-col h-full w-full bg-[#09090b] overflow-hidden min-h-0">
      {/* Top Toolbar Strip */}
      <div className="h-12 border-b border-white/10 px-4 sm:px-6 flex items-center justify-between bg-[#141416]/90 backdrop-blur-md shrink-0 z-10">
        {/* Left Side: Code vs Preview Switcher */}
        <div className="flex items-center gap-1 bg-[#0d0d0f] border border-white/10 rounded-lg p-1">
          <button
            type="button"
            onClick={() => setActiveTab("code")}
            className={`flex items-center gap-1.5 px-3 py-1 text-xs font-bold rounded-md transition-all cursor-pointer ${
              activeTab === "code"
                ? "bg-white text-black shadow-sm"
                : "text-zinc-400 hover:text-white"
            }`}
          >
            <Code2 className="h-3.5 w-3.5" />
            <span>Code</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("preview")}
            className={`flex items-center gap-1.5 px-3 py-1 text-xs font-bold rounded-md transition-all cursor-pointer ${
              activeTab === "preview"
                ? "bg-white text-black shadow-sm"
                : "text-zinc-400 hover:text-white"
            }`}
          >
            <Eye className="h-3.5 w-3.5" />
            <span>Preview</span>
          </button>
        </div>

        {/* Center: File or project title badge */}
        <div className="hidden md:flex items-center gap-2">
          <span className="text-[11px] text-zinc-400 font-mono bg-white/[0.04] border border-white/10 px-2.5 py-1 rounded-md max-w-[240px] truncate">
            {activeTab === "code" ? sandpack.activeFile : projectUrl}
          </span>
        </div>

        {/* Right Side Actions: Copy, Improve & Download */}
        <div className="flex items-center gap-2 sm:gap-2.5">
          <button
            type="button"
            onClick={handleCopyCode}
            className="flex items-center gap-1.5 bg-white/[0.05] border border-white/10 hover:border-white/20 text-zinc-300 hover:text-white rounded-lg px-2.5 py-1.5 text-xs font-medium transition-all active:scale-[0.98] cursor-pointer"
            title="Copy current file code"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">Copy</span>
              </>
            )}
          </button>

          {onImprove && (
            <button
              type="button"
              onClick={() => onImprove("Agent Optimization")}
              disabled={isImproving || isGenerating}
              className="flex items-center gap-1.5 bg-gradient-to-r from-blue-500/15 to-violet-500/15 border border-blue-500/30 text-blue-400 hover:border-blue-500/50 rounded-lg px-3 py-1.5 text-xs font-bold transition-all active:scale-[0.98] cursor-pointer disabled:opacity-50"
            >
              {isImproving ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Wand2 className="h-3.5 w-3.5" />
              )}
              <span>Improve with Agent {isProUser ? "(Pro)" : ""}</span>
            </button>
          )}

          <button
            type="button"
            onClick={handleDownloadCode}
            className="flex items-center gap-1.5 bg-white/[0.05] border border-white/10 hover:border-white/20 text-white rounded-lg px-3 py-1.5 text-xs font-bold transition-all active:scale-[0.98] cursor-pointer"
            title="Download current file"
          >
            <Download className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Download</span>
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 w-full relative overflow-hidden bg-[#09090b] min-h-0">
        {/* Preview View */}
        <div
          className={`absolute inset-0 p-3 sm:p-5 flex flex-col min-h-0 ${
            activeTab === "preview" ? "flex" : "hidden"
          }`}
        >
          {/* macOS Browser Mockup Wrapper */}
          <div className="w-full h-full flex flex-col rounded-xl border border-white/10 bg-[#141416] shadow-2xl overflow-hidden relative min-h-0">
            {/* Browser Address Bar Header */}
            <div className="h-10 border-b border-white/10 px-3.5 bg-[#0f0f13] flex items-center justify-between shrink-0 select-none">
              <div className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-full bg-red-500/40 border border-red-500/30" />
                <span className="h-2.5 w-2.5 rounded-full bg-yellow-500/40 border border-yellow-500/30" />
                <span className="h-2.5 w-2.5 rounded-full bg-green-500/40 border border-green-500/30" />
              </div>

              <div className="flex items-center justify-center flex-1 max-w-md mx-3">
                <div className="w-full bg-[#18181e] border border-white/5 rounded-md px-3 py-1 text-[11px] font-mono text-zinc-400 text-center truncate">
                  {projectUrl}
                </div>
              </div>

              <div className="flex items-center gap-1.5 text-zinc-400">
                <button
                  type="button"
                  onClick={() => refresh()}
                  className="p-1 hover:text-white rounded transition-colors cursor-pointer"
                  title="Reload Sandbox"
                >
                  <RotateCcw className="h-3.5 w-3.5" />
                </button>
                <button
                  type="button"
                  onClick={() => refresh()}
                  className="p-1 hover:text-white rounded transition-colors cursor-pointer"
                  title="Refresh View"
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>

            {/* Sandpack Live Preview Area */}
            <div className="flex-1 w-full h-full relative bg-[#0b0b0f] overflow-hidden min-h-0">
              {isGenerating && (
                <div className="absolute inset-0 bg-[#09090b]/85 backdrop-blur-sm z-20 flex flex-col items-center justify-center gap-3">
                  <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
                  <div className="text-center">
                    <p className="text-sm font-bold text-white">Compiling Sandbox AST</p>
                    <p className="text-xs text-zinc-400 mt-1">
                      Applying real-time code modifications...
                    </p>
                  </div>
                </div>
              )}
              <SandpackPreview
                style={{ height: "100%", width: "100%" }}
                showOpenInCodeSandbox={false}
                showRefreshButton={false}
                showSandpackErrorOverlay={true}
              />
            </div>
          </div>
        </div>

        {/* Code Editor View */}
        <div
          className={`absolute inset-0 overflow-hidden min-h-0 ${
            activeTab === "code" ? "flex" : "hidden"
          }`}
        >
          <div className="flex h-full w-full overflow-hidden min-h-0">
            <SandpackFileExplorer
              style={{
                height: "100%",
                minWidth: "180px",
                maxWidth: "220px",
                background: "#0c0c0e",
                borderRight: "1px solid rgba(255, 255, 255, 0.08)",
              }}
            />
            <div data-lenis-prevent className="flex-1 h-full min-w-0 min-h-0 overflow-hidden flex flex-col">
              <SandpackCodeEditor
                style={{
                  height: "100%",
                  width: "100%",
                  background: "#09090b",
                }}
                showLineNumbers
                showInlineErrors
                wrapContent
                closableTabs
                initMode="immediate"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function CodePanel({
  fileData,
  isGenerating = false,
  statusLog = [],
  onImprove,
  onFixError,
  onFilePatch,
  appTitle = null,
  isImproving = false,
  isProUser = false,
}: CodePanelProps) {
  const [activeTab, setActiveTab] = useState<ActiveTab>("preview");

  const files = {
    "/public/index.html": {
      code: `<!DOCTYPE html>
<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>webIQ App</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      * { box-sizing: border-box; }
      html, body, #root {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
        background-color: #0b0b0f;
        color: #f4f4f5;
        overflow-x: hidden;
        overflow-y: auto;
      }
    </style>
  </head>
  <body class="bg-[#0b0b0f] text-white">
    <div id="root"></div>
  </body>
</html>`,
      hidden: true,
    },
    "/styles.css": {
      code: `* {
  box-sizing: border-box;
}
html, body, #root {
  height: 100%;
  width: 100%;
  margin: 0;
  padding: 0;
  background-color: #0b0b0f;
  color: #f4f4f5;
  overflow-x: hidden;
  overflow-y: auto;
}`,
      hidden: true,
    },
    ...(fileData?.files && Object.keys(fileData.files).length > 0
      ? fileData.files
      : PLACEHOLDER_FILES),
  };

  const dependencies = {
    ...BASE_DEPENDENCIES,
    ...(fileData?.dependencies ?? {}),
  };

  const filePathKey = Object.keys(files).sort().join("|");

  return (
    <div data-lenis-prevent className="flex flex-col flex-1 h-full w-full bg-background overflow-hidden relative min-h-0">
      {/* Global CSS overrides for Sandpack to ensure 100% height and smooth scrolling */}
      <style
        dangerouslySetInnerHTML={{
          __html: `
            .sp-wrapper,
            .sp-layout {
              height: 100% !important;
              min-height: 100% !important;
              width: 100% !important;
              flex: 1 1 0% !important;
              border: none !important;
              background: transparent !important;
            }
            .sp-stack,
            .sp-editor {
              height: 100% !important;
              width: 100% !important;
              flex: 1 1 0% !important;
              display: flex !important;
              flex-direction: column !important;
              overflow: hidden !important;
              border: none !important;
              background: #09090b !important;
            }
            .sp-code-editor {
              height: 100% !important;
              width: 100% !important;
              flex: 1 1 0% !important;
              display: flex !important;
              flex-direction: column !important;
              overflow: hidden !important;
              background: #09090b !important;
            }
            .sp-cm {
              height: 100% !important;
              width: 100% !important;
              flex: 1 1 0% !important;
              display: flex !important;
              flex-direction: column !important;
              overflow: hidden !important;
            }
            .cm-editor {
              height: 100% !important;
              width: 100% !important;
              display: flex !important;
              flex-direction: column !important;
              flex: 1 1 0% !important;
              background: #09090b !important;
            }
            .cm-scroller {
              height: 100% !important;
              width: 100% !important;
              overflow-x: auto !important;
              overflow-y: scroll !important;
              -webkit-overflow-scrolling: touch !important;
              scrollbar-gutter: stable;
            }
            .cm-scroller::-webkit-scrollbar {
              width: 10px;
              height: 10px;
              display: block !important;
            }
            .cm-scroller::-webkit-scrollbar-track {
              background: #09090b !important;
            }
            .cm-scroller::-webkit-scrollbar-thumb {
              background: rgba(255, 255, 255, 0.25) !important;
              border-radius: 5px !important;
              border: 2px solid #09090b !important;
            }
            .cm-scroller::-webkit-scrollbar-thumb:hover {
              background: rgba(255, 255, 255, 0.45) !important;
            }
            .cm-content {
              padding-bottom: 140px !important;
            }
            .cm-line {
              user-select: text !important;
            }
            .sp-file-explorer {
              height: 100% !important;
              min-height: 100% !important;
              overflow-y: auto !important;
              background: #0c0c0e !important;
              border-right: 1px solid rgba(255, 255, 255, 0.08) !important;
            }
            .sp-preview,
            .sp-preview-container {
              height: 100% !important;
              min-height: 100% !important;
              width: 100% !important;
              flex: 1 1 0% !important;
              background: #0b0b0f !important;
              border: none !important;
            }
            .sp-preview-iframe {
              height: 100% !important;
              min-height: 100% !important;
              width: 100% !important;
              background: #0b0b0f !important;
              border: none !important;
            }
          `,
        }}
      />
      <SandpackProvider
        key={filePathKey}
        files={files}
        theme={customTheme}
        customSetup={{ dependencies }}
        template="react"
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          flex: 1,
        }}
        className="!h-full !w-full flex flex-col flex-1 min-h-0"
        options={{
          externalResources: ["https://cdn.tailwindcss.com"],
          recompileMode: "delayed",
          recompileDelay: 300,
        }}
      >
        <SandpackInner
          isGenerating={isGenerating}
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          fileData={fileData}
          onImprove={onImprove}
          isImproving={isImproving}
          isProUser={isProUser}
          appTitle={appTitle}
        />
      </SandpackProvider>
    </div>
  );
}

export default CodePanel;
