"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Link2, Code, Terminal, CheckCircle2, ChevronRight } from "lucide-react";

interface Integration {
  id: string;
  name: string;
  desc: string;
  status: "Native" | "Beta" | "Official";
  glowColor: string; // Tailwind glow border color
  icon: React.ReactNode;
  codeSnippet: string;
  codeLanguage: string;
  codeFilename: string;
}

export default function Integrations() {
  const [activeIntegrationId, setActiveIntegrationId] = useState("supabase");

  const integrations: Integration[] = [
    {
      id: "supabase",
      name: "Supabase",
      desc: "Connect postgres databases and auth instances directly inside the AST sync engine.",
      status: "Native",
      glowColor: "group-hover:border-emerald-500/40 group-hover:shadow-[0_0_30px_rgba(16,185,129,0.15)]",
      icon: (
        <svg className="h-6 w-6 fill-current text-emerald-400" viewBox="0 0 24 24">
          <path d="M21.36 11.1H13.6l5.77-9.45c.42-.68-.13-1.54-.92-1.42l-13.4 2.1c-.65.1-1.04.77-.73 1.3L10.4 12.9h7.76l-5.77 9.45c-.42.68.13 1.54.92 1.42l13.4-2.1c.65-.1 1.04-.77.73-1.3l-6.08-9.27z" />
        </svg>
      ),
      codeFilename: "lib/supabase.ts",
      codeLanguage: "typescript",
      codeSnippet: `import { createClient } from '@supabase/supabase-js';

// Auto-generated by webIQ Database Agent
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export async function fetchLiveAnalytics() {
  const { data, error } = await supabase
    .from('analytics_logs')
    .select('id, user_id, event_type, created_at')
    .order('created_at', { ascending: false })
    .limit(10);
    
  if (error) throw new Error(error.message);
  return data;
}`
    },
    {
      id: "github",
      name: "GitHub",
      desc: "Auto-commit sandbox branches and open pull requests automatically on save.",
      status: "Official",
      glowColor: "group-hover:border-white/30 group-hover:shadow-[0_0_30px_rgba(255,255,255,0.1)]",
      icon: (
        <svg className="h-6 w-6 fill-current text-white" viewBox="0 0 24 24">
          <path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.166 6.839 9.489.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.7-2.782.603-3.369-1.34-3.369-1.34-.454-1.156-1.11-1.462-1.11-1.462-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.831.092-.646.35-1.086.636-1.336-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.025 2.747-1.025.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.577.688.479C19.138 20.162 22 16.418 22 12c0-5.523-4.477-10-10-10z" />
        </svg>
      ),
      codeFilename: ".github/workflows/webiq-sync.yml",
      codeLanguage: "yaml",
      codeSnippet: `name: webIQ Visual Sync Pipeline
on:
  push:
    branches: [ "webiq-*" ]

jobs:
  merge-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: AST Code Health Validation
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Auto-Merge Sandbox Branch
        uses: devops-infra/action-pull-request@v2`
    },
    {
      id: "vercel",
      name: "Vercel",
      desc: "Trigger edge-optimized serverless deployments directly when publishing changes.",
      status: "Native",
      glowColor: "group-hover:border-white/30 group-hover:shadow-[0_0_30px_rgba(255,255,255,0.1)]",
      icon: (
        <svg className="h-6 w-6 fill-current text-white" viewBox="0 0 24 24">
          <path d="M12 2L24 22H0L12 2Z" />
        </svg>
      ),
      codeFilename: "api/vercel-webhook.ts",
      codeLanguage: "typescript",
      codeSnippet: `import type { NextApiRequest, NextApiResponse } from 'next';

// Auto-generated by webIQ Deployment Hook Agent
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { projectId, deployUrl } = req.body;

  // Sync state metadata database
  console.log(\`Project \${projectId} successfully deployed to: \${deployUrl}\`);

  return res.status(200).json({ 
    synced: true, 
    deployedAt: new Date().toISOString() 
  });
}`
    },
    {
      id: "tailwind",
      name: "Tailwind CSS",
      desc: "Instant dynamic theme configuration injection and custom style generation.",
      status: "Native",
      glowColor: "group-hover:border-cyan-400/40 group-hover:shadow-[0_0_30px_rgba(34,211,238,0.15)]",
      icon: (
        <svg className="h-6 w-6 fill-current text-cyan-400" viewBox="0 0 24 24">
          <path d="M12.001 4.8c-3.2 0-5.2 1.6-6 4.8 1.2-1.6 2.6-2.2 4.2-1.8 0.916.229 1.57.892 2.295 1.628C13.686 10.651 14.86 11.8 18.001 11.8c3.2 0 5.2-1.6 6-4.8-1.2 1.6-2.6 2.2-4.2 1.8-.915-.229-1.57-.892-2.295-1.628C16.316 6.149 15.143 5 12.001 5zm-6 7c-3.2 0-5.2 1.6-6 4.8 1.2-1.6 2.6-2.2 4.2-1.8.916.229 1.57.892 2.295 1.628C7.686 17.651 8.86 18.8 12.001 18.8c3.2 0 5.2-1.6 6-4.8-1.2 1.6-2.6 2.2-4.2 1.8-.915-.229-1.57-.892-2.295-1.628C10.316 13.149 9.143 12 6.001 12z" />
        </svg>
      ),
      codeFilename: "tailwind.config.ts",
      codeLanguage: "typescript",
      codeSnippet: `import type { Config } from 'tailwindcss';

// Auto-injected visual theme configurations
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: '#090909',
        surface: {
          1: '#141414',
          2: '#1c1c1c',
        },
        accent: {
          blue: '#0099ff',
          violet: '#6a4cf5',
        }
      }
    }
  }
} satisfies Config;`
    }
  ];

  const activeIntegration = integrations.find((i) => i.id === activeIntegrationId) || integrations[0];

  return (
    <section id="integrations" className="w-full max-w-[1200px] mx-auto px-6 md:px-8 py-24 border-t border-hairline-soft relative">
      {/* Background ambient spotlight */}
      <div className="absolute top-[20%] left-[50%] -translate-x-1/2 w-[500px] h-[300px] rounded-full bg-gradient-orange/5 glow-blur pointer-events-none"></div>

      {/* Section Header */}
      <div className="mb-16 text-center">
        <span className="text-[13px] font-semibold uppercase tracking-[0.2em] text-accent-blue bg-accent-blue/10 px-3 py-1 rounded-full">
          Ecosystem
        </span>
        <h2 className="font-heading text-4xl md:text-5xl font-medium tracking-[-0.04em] text-white mt-4 mb-4 uppercase">
          Fits into your tech stack.
        </h2>
        <p className="max-w-xl mx-auto text-ink-muted text-base leading-relaxed tracking-[-0.015em]">
          webIQ exports standard React, Next.js, and Tailwind assets that connect natively to the backend platforms you already run.
        </p>
      </div>

      {/* Main Grid: Left is Cards, Right is Code Showcase */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
        
        {/* Left Side: Integrations Grid */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          {integrations.map((i) => {
            const isActive = i.id === activeIntegrationId;
            return (
              <button
                key={i.id}
                onClick={() => setActiveIntegrationId(i.id)}
                className={`group text-left border rounded-[20px] p-5 transition-all duration-300 relative overflow-hidden flex gap-4 select-none focus:outline-none ${
                  isActive
                    ? "bg-[#141414] border-hairline shadow-xl scale-[1.01]"
                    : "bg-surface-1/40 border-transparent hover:border-hairline/50 hover:bg-surface-1/60"
                } ${i.glowColor}`}
              >
                {/* Brand Icon Container */}
                <div className={`h-11 w-11 shrink-0 rounded-xl border flex items-center justify-center transition-all duration-300 ${
                  isActive ? "bg-surface-2 border-hairline/80" : "bg-[#090909] border-hairline"
                }`}>
                  {i.icon}
                </div>

                {/* Details */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-2">
                    <h3 className="font-heading text-[15px] font-bold text-white tracking-tight">
                      {i.name}
                    </h3>
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                      i.status === "Native"
                        ? "bg-accent-blue/10 text-accent-blue border border-accent-blue/10"
                        : "bg-surface-2 text-ink-muted border border-hairline"
                    }`}>
                      {i.status}
                    </span>
                  </div>
                  <p className="text-[12.5px] leading-relaxed text-ink-muted mt-2 tracking-[-0.01em]">
                    {i.desc}
                  </p>
                </div>
              </button>
            );
          })}
        </div>

        {/* Right Side: Code Viewer */}
        <div className="lg:col-span-7 bg-[#141414] border border-hairline rounded-[24px] p-5 shadow-2xl flex flex-col justify-between relative overflow-hidden min-h-[380px]">
          
          {/* Top Frame Control */}
          <div className="flex items-center justify-between border-b border-hairline pb-4 mb-4 select-none">
            <div className="flex items-center gap-2">
              <span className="h-3 w-3 rounded-full bg-[#1c1c1c] border border-hairline"></span>
              <span className="text-[11px] text-ink-muted font-mono ml-2">
                {activeIntegration.codeFilename}
              </span>
            </div>
            <div className="flex items-center gap-1.5 bg-[#090909] border border-hairline px-3 py-1 rounded-lg">
              <Code className="h-3.5 w-3.5 text-accent-blue" />
              <span className="text-[10.5px] text-ink-muted font-mono">Sync Code Output</span>
            </div>
          </div>

          {/* Code Snippet Box */}
          <div className="flex-1 bg-[#090909] border border-hairline rounded-xl p-4 overflow-y-auto max-h-[320px] font-mono text-[11px] leading-relaxed text-zinc-300">
            <pre className="font-mono">
              <code className="font-mono">
                {activeIntegration.codeSnippet}
              </code>
            </pre>
          </div>

          {/* Bottom Summary Bar */}
          <div className="mt-4 pt-3 border-t border-hairline/40 flex items-center justify-between text-[11px] font-medium text-ink-muted select-none">
            <span className="flex items-center gap-1.5">
              <CheckCircle2 className="h-4.5 w-4.5 text-emerald-400 shrink-0" />
              Production-ready assets synced cleanly
            </span>
            <span className="font-mono text-[10px] uppercase">
              {activeIntegration.codeLanguage}
            </span>
          </div>

        </div>

      </div>
    </section>
  );
}
