"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";
import { UserButton, useUser } from "@clerk/nextjs";
import { getOrCreateUserAction } from "@/actions/user";
import { PLANS } from "@/lib/constants";
import PlanModal from "@/components/PlanModal";
import { ChatPanel } from "@/components/ChatPanel";
import { CodePanel } from "@/components/CodePanel";
import { Message, FileData, StatusStep } from "@/types/workspace";
import {
  ArrowLeft,
  RotateCcw,
  Zap,
  Loader2,
} from "lucide-react";

interface WorkspaceClientProps {
  initialPrompt: string;
}

const generateCodeForPrompt = (prompt: string): string => {
  const cleanTitle = prompt.replace(/"/g, '\\"');
  return `import React, { useState } from 'react';
import { Sparkles, Terminal, Heart, Zap, CheckCircle, ArrowUpRight } from 'lucide-react';

export default function App() {
  const [likes, setLikes] = useState(12);

  return (
    <div className="min-h-screen bg-[#0b0b0f] text-white p-4 sm:p-8 font-sans flex flex-col items-center justify-center antialiased">
      <div className="w-full max-w-xl bg-[#14141c]/90 border border-white/10 rounded-2xl p-6 sm:p-8 shadow-2xl backdrop-blur-xl relative overflow-hidden">
        {/* Glow accent */}
        <div className="absolute -top-24 -right-24 w-48 h-48 bg-blue-500/20 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -bottom-24 -left-24 w-48 h-48 bg-purple-500/15 rounded-full blur-3xl pointer-events-none" />

        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4 mb-6">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-400">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-base sm:text-lg font-bold text-white tracking-tight capitalize">${cleanTitle}</h1>
              <p className="text-xs text-zinc-400">Generated by webIQ AI Sandbox</p>
            </div>
          </div>
          <span className="inline-flex items-center gap-1.5 text-[11px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2.5 py-1 rounded-full">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            Active
          </span>
        </div>

        {/* Content body */}
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5 hover:border-white/10 transition-colors">
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs text-zinc-400">Performance</span>
                <Zap className="w-3.5 h-3.5 text-amber-400" />
              </div>
              <p className="text-2xl font-bold text-white">99.4%</p>
            </div>
            <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5 hover:border-white/10 transition-colors">
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs text-zinc-400">AST Nodes</span>
                <CheckCircle className="w-3.5 h-3.5 text-blue-400" />
              </div>
              <p className="text-2xl font-bold text-white">48</p>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5 text-xs text-zinc-300 leading-relaxed">
            <p>
              This component is rendered live in your active sandbox. Use the chat panel on the left to ask for new features, adjust styling, or inspect code in the Code tab.
            </p>
          </div>

          {/* Interactive CTAs */}
          <div className="flex items-center gap-3 pt-2">
            <button
              onClick={() => setLikes((l) => l + 1)}
              className="flex-1 py-2.5 px-4 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-semibold transition-all flex items-center justify-center gap-2 shadow-lg shadow-blue-600/20 cursor-pointer active:scale-[0.98]"
            >
              <Heart className="w-4 h-4 fill-white" />
              <span>Applaud ({likes})</span>
            </button>
            <button
              onClick={() => alert("webIQ Sandbox active and responsive!")}
              className="py-2.5 px-4 bg-white/5 hover:bg-white/10 text-zinc-200 hover:text-white border border-white/10 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 cursor-pointer active:scale-[0.98]"
            >
              <span>Explore</span>
              <ArrowUpRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}`;
};

export default function WorkspaceClient({ initialPrompt }: WorkspaceClientProps) {
  // Auth & User State
  const { isSignedIn, isLoaded } = useUser();
  const [dbUser, setDbUser] = useState<{ credits: number; plan: string } | null>(null);
  const [isCreditsModalOpen, setIsCreditsModalOpen] = useState(false);

  useEffect(() => {
    if (isLoaded && isSignedIn) {
      getOrCreateUserAction().then((u) => {
        if (u) setDbUser(u);
      });
    }
  }, [isLoaded, isSignedIn]);

  const maxCredits = dbUser ? (PLANS[dbUser.plan as keyof typeof PLANS]?.credits || 10) : 10;

  // Workspace View & Execution State
  const [generationLogs, setGenerationLogs] = useState<string[]>([]);
  const [statusLogs, setStatusLogs] = useState<StatusStep[]>([]);
  const [isCompiling, setIsCompiling] = useState(true);
  const [fileData, setFileData] = useState<FileData | null>(null);

  // Chat State
  const [chatMessages, setChatMessages] = useState<Message[]>([]);

  const runCompilationSimulation = useCallback((promptText: string) => {
    const logs = [
      "Initializing agentic sandbox environment...",
      "Analyzing request parameters...",
      `Parsing AST prompt: "${promptText.slice(0, 35)}..."`,
      "Creating component structure and layout tree...",
      "Injecting TailwindCSS variables...",
      "Compilation Successful! 0 errors.",
    ];

    setGenerationLogs([]);
    setStatusLogs([]);
    setIsCompiling(true);

    let currentLogIndex = 0;
    const interval = setInterval(() => {
      if (currentLogIndex < logs.length) {
        const nextLog = logs[currentLogIndex];
        setGenerationLogs((prev) => [...prev, nextLog]);
        setStatusLogs((prev) => [
          ...prev,
          { label: nextLog, status: currentLogIndex === logs.length - 1 ? "done" : "running" },
        ]);
        currentLogIndex++;
      } else {
        setIsCompiling(false);
        setFileData({
          files: {
            "/App.js": {
              code: generateCodeForPrompt(promptText),
            },
          },
          dependencies: {
            "lucide-react": "latest",
          },
          title: promptText,
        });
        clearInterval(interval);
      }
    }, 400);
  }, []);

  // Initial prompt setup
  useEffect(() => {
    const timer = setTimeout(() => {
      const timeStr = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      setChatMessages([
        {
          id: "msg-1",
          role: "assistant",
          content: `Hello! I'm your webIQ AI Agent. I have initialized the workspace for your prompt:\n\n"${initialPrompt}"\n\nYou can refine the code, ask for new components, or upload design mockups.`,
          timestamp: timeStr,
        },
      ]);

      runCompilationSimulation(initialPrompt);
    }, 0);

    return () => clearTimeout(timer);
  }, [initialPrompt, runCompilationSimulation]);

  const handleSendMessage = (userMsgText: string, image?: string) => {
    const timeStr = new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

    const userMsg: Message = {
      id: `msg-${Date.now()}`,
      role: "user",
      content: userMsgText,
      imageUrl: image,
      timestamp: timeStr,
    };

    setChatMessages((prev) => [...prev, userMsg]);

    // Trigger AI response simulation
    setTimeout(() => {
      const aiMsg: Message = {
        id: `msg-${Date.now() + 1}`,
        role: "assistant",
        content: `Updating webIQ sandbox with your new instruction: "${userMsgText}". Re-compiling component tree.`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setChatMessages((prev) => [...prev, aiMsg]);
      runCompilationSimulation(userMsgText || "Updated layout");
    }, 500);
  };

  const handleImprove = (userRequest: string) => {
    handleSendMessage(`Improve and optimize component: ${userRequest}`);
  };

  return (
    <div data-lenis-prevent className="h-screen w-screen bg-[#09090b] text-white font-sans flex flex-col justify-between overflow-hidden">
      {/* Header matching Navbar style */}
      <header className="h-14 border-b border-white/10 bg-[#141416]/80 backdrop-blur-md px-4 sm:px-6 flex items-center justify-between z-20 shrink-0">
        <div className="flex items-center gap-3 sm:gap-4">
          <Link
            href="/"
            className="p-1.5 rounded-lg border border-white/5 bg-white/[0.02] hover:bg-white/[0.08] transition-all text-zinc-400 hover:text-white"
            title="Back to Home"
          >
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <div className="h-4 w-px bg-white/10 hidden sm:block"></div>
          <span className="font-geist text-lg font-bold tracking-tight flex items-center gap-1.5">
            web<span className="text-accent-blue">IQ</span>
            <span className="text-xs text-zinc-400 font-normal">Workspace</span>
          </span>
          <span className="hidden md:inline-flex text-[10px] font-bold uppercase tracking-wider bg-accent-blue/10 border border-accent-blue/20 text-accent-blue px-2.5 py-0.5 rounded-full">
            Sandbox Active
          </span>
        </div>

        {/* Right Header CTAs & User Credits */}
        <div className="flex items-center gap-2.5 sm:gap-3">
          <button
            onClick={() => runCompilationSimulation(initialPrompt)}
            className="hidden sm:flex items-center gap-1.5 bg-[#1a1a1e] border border-white/10 hover:border-white/20 rounded-full px-3 py-1.5 font-sans text-xs font-semibold text-zinc-300 transition-all active:scale-[0.98] cursor-pointer"
          >
            <RotateCcw className="h-3.5 w-3.5" /> Reset Sandbox
          </button>

          {/* Dynamic Credits Badge */}
          <button
            onClick={() => setIsCreditsModalOpen(true)}
            className="flex items-center gap-1.5 bg-white/[0.05] border border-white/10 rounded-full px-3 py-1.5 font-sans text-[12px] font-medium text-zinc-300 select-none cursor-pointer transition-all hover:bg-white/[0.1] active:scale-[0.98]"
          >
            <Zap className="h-3.5 w-3.5 text-zinc-300 fill-zinc-300/10" />
            <span className="tracking-tight flex items-center gap-1.5">
              {dbUser ? (
                `${dbUser.credits} / ${maxCredits} credits`
              ) : (
                <>
                  <Loader2 className="h-3 w-3 animate-spin text-accent-blue" />
                  <span className="text-[11px] text-zinc-500">loading...</span>
                </>
              )}
            </span>
          </button>

          {/* User Button */}
          <UserButton />
        </div>
      </header>

      {/* Main Workspace: ChatPanel on the Left, CodePanel on the Right */}
      <main className="flex-1 grid grid-cols-1 lg:grid-cols-12 overflow-hidden h-[calc(100vh-56px)]">
        {/* Left Column: Chat Panel */}
        <div className="lg:col-span-4 h-full overflow-hidden border-r border-white/10 flex flex-col min-h-0">
          <ChatPanel
            messages={chatMessages}
            onSendMessage={handleSendMessage}
            isGenerating={isCompiling}
            statusLogs={generationLogs}
          />
        </div>

        {/* Right Column: Sandpack Code & Live Preview Panel */}
        <div className="lg:col-span-8 h-full overflow-hidden flex flex-col min-h-0">
          <CodePanel
            fileData={fileData}
            isGenerating={isCompiling}
            statusLog={statusLogs}
            onImprove={handleImprove}
            appTitle={initialPrompt}
            isProUser={dbUser?.plan !== "free"}
          />
        </div>
      </main>

      {/* Plan Modal */}
      {dbUser && (
        <PlanModal
          isOpen={isCreditsModalOpen}
          onClose={() => setIsCreditsModalOpen(false)}
          credits={dbUser.credits}
          maxCredits={maxCredits}
          planName={dbUser.plan}
          onUpgradeClick={() => {
            setIsCreditsModalOpen(false);
            window.location.href = "/#pricing";
          }}
        />
      )}
    </div>
  );
}